name: hospital
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
   


 
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0



flutter:

 

  uses-material-design: true

 

